/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javahw4;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.mockito.Mockito;

import javahw4.Calculator.IAdder;
import javahw4.Calculator.IFlipper;
import javahw4.Calculator.ISubtractor;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class SubtractorTest{
    private ISubtractor subtractor;

    @BeforeAll
    public void setUp(){
        IAdder adder = Mockito.mock(IAdder.class);
        IFlipper flipper = Mockito.mock(IFlipper.class);

        Mockito.when(flipper.flip(5)).thenReturn(-5);
        Mockito.when(adder.add(3, -5)).thenReturn(-2);
        subtractor = new Subtractor(adder, flipper);
    }
    @Test
    public void substractTest(){
        Assertions.assertEquals(-2, subtractor.subtract(3, 5));
    }
}